# Generated by Django 4.2 on 2023-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
