# Generated by Django 4.2 on 2023-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('To be sent', 'DO wysłania'), ('Woman', 'Woman')], max_length=10, null=True),
        ),
    ]
