# Generated by Django 4.2 on 2023-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_order_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('1', 'Do wysłania'), ('2', 'Wysłana')], default='To be sent', max_length=10, null=True),
        ),
    ]
