# Generated by Django 4.2 on 2023-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_order_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(choices=[('Do wysłania', 'Do wysłania'), ('Wysłana', 'Wysłana'), ('Dostarczona', 'Dostarczona')], default='Do wysłania', max_length=15, null=True),
        ),
    ]
