# Generated by Django 4.2 on 2023-04-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_cupon_discount_alter_itemvariant_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsize',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.category'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Jeśli przedmiot jest uniwersalnego rozmiaru zostaw to pole puste', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_size', to='App.itemsize'),
        ),
    ]
