# Generated by Django 4.2 on 2023-04-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_itemsize_category_alter_itemvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsize',
            name='category',
        ),
        migrations.AddField(
            model_name='itemsize',
            name='category',
            field=models.ManyToManyField(null=True, to='App.category'),
        ),
    ]
