# Generated by Django 4.2 on 2023-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_itemsize_category_itemsize_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='category',
            field=models.ManyToManyField(to='App.category'),
        ),
    ]
