# Generated by Django 4.2 on 2023-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_itemsize_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='display_on_page',
            field=models.BooleanField(default=False),
        ),
    ]
