# Generated by Django 4.2 on 2023-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_cupon_display_on_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
